
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
shell = "/bin/zsh"

[font]
size = 17.0

[font.normal]
family = "MesloLGS NF"



[window]
#decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10

