
[font]
size = 12.0

[font.normal]
family = "MesloLGLDZ Nerd Font Mono"



[window]
#decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10

[general]

import = ["~/.config/alacritty/themes/themes/mmaterial_theme.toml"]

[terminal]
shell = "/bin/zsh"

