#!/bin/bash
 
WALLPAPER=~/Pictures/wallpaper/cat.jpg

xsetroot -cursor_name left_ptr &
sxhkd & # Shortcuts
xrandr --output edP-1 --mode 1920x1080 & # Screen Options
xautolock -time 5 -nowlocker "betterlockscreen -l dimblur -q -u $WALLPAPER" -locker "~/.config/sxhkd/lock.sh" -detectsleep -killtime 10 -killer 'systemctl hibernate' &
feh --bg-scale $WALLPAPER # Background Image
polybar example & # Top bar
dunst & # Starting notification daemon
picom & # Compositor
/home/sol/.config/bspwm/autostart.sh
setxkbmap de


bspc monitor -d I II III IV V VI VII VIII IX X
 
bspc config border_width	1
bspc config window_gap		5
 
bspc config split_ratio		0.50
#bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod4

bspc config pointer_action1 resize_side
bspc config pointer_action3 move
#bspc config pointer_actioni resize_corner

bspc config automatic_scheme alternate	

bspc rule -a krunner state=floating
bspc rule -a discord state=floating
bspc rule -a dolphin state=floating
bspc rule -a Thunar state=floating
bspc rule -a rustdesk state=floating
bspc rule -a "KeePassXC" state=floating
bspc rule -a alacritty_taskmanager state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Shutter state=floating
bspc rule -a xfreerdp state=floating
bspc rule -a "qemu-system-x86_64" state=tiled

