#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd & # Shortcuts
xrandr --output edP-1 --mode 1920x1080 # Screen Options
feh --bg-scale /usr/share/wallpapers/North/contents/images_dark/5120x2880.png # Background Image
polybar example & # Top bar
dunst & # Starting notification daemon

bspc monitor -d I II III IV V
 
bspc config border_width	3
bspc config window_gap		0
 
bspc config split_ratio		0.60
#bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod4

bspc config pointer_action1 resize_side
bspc config pointer_action3 move
#bspc config pointer_actioni resize_corner

bspc config automatic_scheme alternate	

bspc rule -a krunner state=floating
bspc rule -a discord desktop='^2' state=floating
bspc rule -a dolphin state=floating
bspc rule -a rustdesk desktop='^2' state=floating
bspc rule -a "KeePassXC" state=floating
